@baseUrl = http://localhost:3000/api


# @name Guest
GET {{baseUrl}}/auth/guest

###

# @name Refresh
GET {{{baseUrl}}/auth/refresh

###

@authToken = {{Guest.response.body.accessToken}}

GET {{baseUrl}}/matching
Authorization: Bearer {{authToken}}

###

# @name CreateUser
@authToken = {{Guest.response.body.accessToken}}

POST {{baseUrl}}/users
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"email": "test@gs.com",
	"name": "test",
	"password": "password"
}


###

# @name Login
@authToken = {{Guest.response.body.accessToken}}

POST {{baseUrl}}/auth/login
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"email": "test@gs.com",
	"password": "password"
}

###

# @name Get

@loggedAuthToken = {{Login.response.body.accessToken}}

GET {{baseUrl}}/users
Authorization: Bearer {{loggedAuthToken}}
Content-Type: application/json


###

GET {{baseUrl}}/users/all
Content-Type: application/json

###

# @name getMovie

@authToken = {{Guest.response.body.accessToken}}

GET {{baseUrl}}/movies/2
Authorization: Bearer {{authToken}}
Content-Type: application/json


###